using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sloader.Switches
{
    class SwitchProperties
    {
        public enum SwitchType
        {
            CS1000,
            SL100,
            fiveEss,
            Ewsd,
            Hipath,
            Avaya,
            Cisco,
            As5300
        }
        
        public enum CS1000Fields
        {
            DN,
            LEN,
            TYPE,
            ClassOfService,
            OPTIONS,
            Key,
            Buttons,
            DES,
            TGAR,
            ACD_PILOT,
            CLID,
            Int_Grp,
            MADN,
            KEY_DIAL_TONE_FEATURE
        }

        public enum AvayaFields
        {
            KEY,
            KEY_TYPE,
            Extension,
            Type,
            Port,
            Name,
            Coverage_Path_1,
            Coverage_Path_2,
            Hunt_to_Station,
            TN,
            COR,
            COS,
            OPTIONS,
            MADN, 
            PrimaryExtension,
            VoiceMail,
            Lock_Messages,
            Security_Code,
            Tests,
            Loss_Group,
            Off_Premises_Station,
            Survivable_COR,
            Survivable_Trunk_Dest,
            Time_of_Day_Lock_Table,
            Message_Waiting_Indicator,
            Message_Lamp_Ext,
            Remote_Office_Phone,
            LWC_Reception,
            LWC_Activation,
            LWC_Log_External_Calls,
            CDR_Privacy,
            Redirect_Notification,
            Per_Button_Ring_Control,
            Bridged_Call_Alerting,
            Switchhook_Flash,
            Ignore_Rotary_Digits,
            H320_Conversion,
            Service_Link_Mode,
            Multimedia_Mode,
            MWI_Served_User_Type,
            AUDIX_Name,
            Recall_Rotary_Digit,
            Emergency_Location_Ext,
            Precedence_Call_Waiting,
            Coverage_Msg_Retrieval,
            Auto_Answer,
            Data_Restriction,
            Call_Waiting_Indication,
            Att_Call_Waiting_Indication,
            Distinctive_Audible_Alert,
            Adjunct_Supervision,
            Per_Station_CPN_Send_Calling_Number,
            Audible_Message_Waiting,
            Coverage_After_Forwarding,
            Multimedia_Early_Answer,
            Direct_IP_IP_Audio_Connections,
            IP_Audio_Hairpinning,
            Bridged_Appearance_Origination_Restriction,
            Internal_Calls_To,
            External_Calls_To,
            Room,
            Jack,
            Cable,
            Floor,
            Building,
            Headset,
            Speaker,
            Mounting,
            Cord_Length,
            Set_Color,
            List1,
            List2,
            List3,
            Abbreviated_Dialing_List_Number_above_123,
            Dial_Code,
            Line_Appearance,
            Data_Option,
            Speakerphone,
            Display_Language,
            Personalized_Ringing_Pattern,
            Mute_Button_Enabled,
            Expansion_Module,
            Media_Complex_Ext,
            IP_Softphone,
            Customizable_Labels,
            Active_Station_Ringing,
            Automatic_Moves,
            Auto_Select_Any_Idle_Appearance,
            Idle_Appearance_Preference,
            Bridged_Idle_Line_Preference,
            Restrict_Last_Appearance,
            EMU_Login_Allowed,
            Display_Client_Redirection,
            Select_Last_Used_Appearance,
            ConfTrans_on_Primary_Appearance,
            Call_Appearance_Display_Format,
            Data_Module,
            Auto_AD,
            Survivable_GK_Node_Name,
            Button_Modules,
            Always_Use,
            IP_Phone_Group_ID,
            R_Balance_Network,
            XID,
            Secure_Terminal_Equip,
            MIM_Support,
            Endpt_Init,
            SPID,
            MIM_MtceMgt,
            Display_Module,
            Coverage_Module,
            Map_to_Station,
            IP_Video_Softphone,
            Remote_Softphone_Emergency_Calls,
            Feature_Module,
            Display_Caller_ID,
            Caller_ID_Message_Waiting_Indication,
            Data_Extension,
            Multimedia,
            SPECIAL_DIALING_OPTION,
            Default_Duplex,
            Default_Mode,
            Default_Speed,
            Default_ITC,
            Default_Data_Application,
            Ext,
            XMOBILE_Type,
            Mobility_Trunk_Group,
            Configuration_Set,
            Dial_Prefix,
            Cell_Phone_Number,
            Message_Waiting_Type,
            Length_of_Display
        }

        public enum CiscoFields
        {

        }

        public enum As5300Fields
        {

        }
    }
}
